# Generated by Django 5.1.2 on 2024-11-20 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0002_alter_article_auteur"),
    ]

    operations = [
        migrations.AddField(
            model_name="article",
            name="is_approved",
            field=models.BooleanField(default=False),
        ),
    ]
